apiVersion: batch/v1
kind: CronJob
metadata:
  name: bourbontracker
  namespace: bourbontracker
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            co.elastic.logs/enabled: "true"
        spec:
          containers:
          - name: bourbontracker
            image: ghcr.io/jeffspahr/bourbontracker:0.1.0
            imagePullPolicy: Always
          restartPolicy: OnFailure
